# Generated by Django 5.0 on 2023-12-11 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_category_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='owner',
        ),
    ]
