# Generated by Django 5.0 on 2023-12-11 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_productattribute_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='product',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
