# Generated by Django 5.0 on 2023-12-12 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_payment_status_remove_payment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cart',
        ),
    ]
